[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
# TODO: update when https://github.com/MakieOrg/Makie.jl/pull/5137 merged
CairoMakie = "0.15.3"

[extras]
NestedNumbers = "1f6363f3-4ba7-41a3-bcac-d685ef427933"

[sources]
NestedNumbers = {url = "https://github.com/JuliaMath/NestedNumbers.jl"}
